/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Path filePath = Paths.get("C:\\Users\\STUDENT\\java-401\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        String errorMsg = javaScriptLinter(filePath);
        System.out.println(errorMsg);
    }

    public static String javaScriptLinter(Path filePath) {
        String line, errorMSGs = "";
        int lineNum = 1;

        try (
                BufferedReader bufferedReader = Files.newBufferedReader(filePath)
        ) {
            while ((line = bufferedReader.readLine()) != null) {
                if (!(line.isBlank() || line.endsWith("{") || line.endsWith("}") || line.contains("if") || line.contains("else") || line.endsWith(";")))
                    errorMSGs += "Line " + lineNum + ": Missing semicolon.\n";
                lineNum++;
            }
        } catch (IOException ioException) {
            System.out.println(ioException.getMessage());
        }
        return errorMSGs;
    }
}
