/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void RestaurantToString(){
        Restaurant restaurant = new Restaurant("500", "$$$");
        String str = restaurant.toString();
        assertEquals(str, restaurant.toString(), "Method should print the reviews of Restaurants");
    }

    @Test
    public void ReviewToString(){
        Review review = new Review("It is amazing restaurant","Mohammad",2);
        String str = review.toString();
        assertEquals(str, review.toString(),"Method should print the reviews of users");
    }

    @Test
    public void isAssociated(){
        Restaurant restaurant = new Restaurant("500", "$$$");
        Review review = new Review("It is amazing restaurant","Mohammad",2);
        restaurant.addReview(review);

        String resStr = restaurant.toString();
        String revStr = review.toString();

        assertTrue(resStr.contains(revStr));
    }

}
