/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void noErrorTester(){
        Path filePath = Paths.get("C:\\Users\\STUDENT\\java-401\\java-fundamentals\\linter\\app\\src\\test\\resources\\emptyFile.js");
        assertEquals("", App.javaScriptLinter(filePath),"it should return empty string");
    }

    @Test void oneErrorsTester(){
        Path filePath = Paths.get("C:\\Users\\STUDENT\\java-401\\java-fundamentals\\linter\\app\\src\\test\\resources\\noError.js");
        assertEquals("Line 2: Missing semicolon.\n",App.javaScriptLinter(filePath), "it should return Line 2: Missing semicolon.");
    }

    @Test void fewErrorsTester(){
        Path filePath = Paths.get("C:\\Users\\STUDENT\\java-401\\java-fundamentals\\linter\\app\\src\\test\\resources\\fewErrors.js");
        assertEquals("Line 3: Missing semicolon.\n" +
                "Line 5: Missing semicolon.\n",App.javaScriptLinter(filePath), "it should return Line 3: Missing semicolon.\n" +
                "Line 5: Missing semicolon.\n");
    }

    @Test void manyError(){
        Path filePath = Paths.get("C:\\Users\\STUDENT\\java-401\\java-fundamentals\\linter\\app\\src\\test\\resources\\manyError.js");
        assertEquals("Line 3: Missing semicolon.\n" +
                "Line 5: Missing semicolon.\n" +
                "Line 11: Missing semicolon.\n" +
                "Line 13: Missing semicolon.\n" +
                "Line 15: Missing semicolon.\n", App.javaScriptLinter(filePath), "it should return Line 3: Missing semicolon.\n" +
                "Line 5: Missing semicolon.\n" +
                "Line 11: Missing semicolon.\n" +
                "Line 13: Missing semicolon.\n" +
                "Line 15: Missing semicolon.\n");
    }

    @Test void emptyFile(){
        Path filePath = Paths.get("C:\\Users\\STUDENT\\java-401\\java-fundamentals\\linter\\app\\src\\test\\resources\\emptyFile.js");
        assertEquals("", App.javaScriptLinter(filePath), "It should return nothing '' ");
    }

}
